# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14E3cFdr_FoHYVJWn1l1INa26VpZ-_m0D
"""

!pip install streamlit

# =========================
# 2. Streamlit Web App
# =========================

# Save this as app.py

import streamlit as st
import matplotlib.pyplot as plt

def load_generator():
    model = Generator()
    model.load_state_dict(torch.load("generator.pt", map_location=torch.device('cpu')))
    model.eval()
    return model

def generate_images(generator, digit, num_samples=5):
    noise = torch.randn(num_samples, z_dim)
    labels = torch.full((num_samples,), digit, dtype=torch.long)
    labels_onehot = torch.nn.functional.one_hot(labels, num_classes=10).float()
    with torch.no_grad():
        fake_images = generator(noise, labels_onehot).view(-1, 28, 28)
    return fake_images

st.title("Handwritten Digit Image Generator")

digit = st.selectbox("Select a digit to generate:", list(range(10)))

if st.button("Generate Images"):
    generator = load_generator()
    images = generate_images(generator, digit)
    fig, axes = plt.subplots(1, 5, figsize=(15, 3))
    for img, ax in zip(images, axes):
        ax.imshow(img.squeeze(), cmap="gray")
        ax.axis("off")
    st.pyplot(fig)

